services:
  - type: web
    name: moon-or-dust-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: ADMIN_CHAT_ID
        fromSecret: ADMIN_CHAT_ID
